_extends: .github

repository:
  name: readme
  description: "Automated GitHub profile readme"
  homepage: "https://github.com/promise"
  private: false
  topics: profile-readme

branches:
  - name: main
    protection:
      required_status_checks:
        checks:
          - context: Recreate README
          - context: ESLint
          - context: CodeQL Analysis
          - context: OSSAR Analysis
          - context: NJS Scan
