# Ths workflow is the secret behind my profile.
# Check it out yourself! => https://github.com/promise

name: README Update

on:
  push:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  main:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript code
        run: npm run build

      - name: Recreate README.md
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit README and push
        run: |
          git config --global user.name "​"
          git config --global user.email "gh-actions@not-tech.support"
          git add README.md
          git commit -m "Update README"
          git push
