# Ths workflow is the secret behind my profile.
# Check it out yourself! => https://github.com/promise

name: README Update

on:
  push:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  main:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript code
        run: npm run build

      - name: Recreate README.md
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: 'profile-automation@but-it-actually.works'
          author_name: '🤖'
          message: "Profile Automation"
          branch: "master"
          force: true
