# Ths workflow is the secret behind my profile.
# Check it out yourself! => https://github.com/promise

name: Profile README

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 */8 * * *' # every 8th hour
  workflow_dispatch:

jobs:
  main:
    name: Recreate README
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Set up node
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
      with:
        node-version: "16.x"

    - name: Restore cached modules
      uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77 # tag=v3
      id: cache-packages
      with:
        path: node_modules
        key: ${{ hashFiles('**/package-lock.json') }}

    - name: Fallback if module cache fails
      run: npm ci
      if: steps.cache-packages.outputs.cache-hit != 'true'

    - name: Build TypeScript
      run: npm run build

    - name: Recreate README
      run: npm start
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        git config --global user.name github-actions[bot]
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add README.md
        git commit -m "Update README" || true
        git push || true
