name: Profile README

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  main:
    name: Recreate README
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Set up node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Restore cached build
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      id: cache-build
      with:
        path: build
        key: ${{ github.sha }}

    - name: Fallback if build cache fails
      run: pnpm build
      if: steps.cache-build.outputs.cache-hit != 'true'

    - name: Recreate README
      run: pnpm start
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push
      if: ${{ github.event_name != 'pull_request' }}
      uses: s0/git-publish-subdir-action@ac113f6bfe8896e85a373534242c949a7ea74c98 # develop
      env:
        REPO: git@github.com:promise/promise.git
        BRANCH: promise
        FOLDER: output
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SQUASH_HISTORY: true
        SKIP_EMPTY_COMMITS: false
        MESSAGE: "chore: profile automation 🎉"
        COMMIT_NAME: "github-actions[bot]"
        COMMIT_EMAIL: "github-actions[bot]@users.noreply.github.com"
